package com.qj.mybatis.mapper;

import com.qj.mybatis.entity.SayUser;


public interface SayUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table say_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table say_user
     *
     * @mbggenerated
     */
    int insert(SayUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table say_user
     *
     * @mbggenerated
     */
    int insertSelective(SayUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table say_user
     *
     * @mbggenerated
     */
    SayUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table say_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SayUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table say_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SayUser record);

    SayUser selectByOpenId(String openId);
}